name: 'Auto Sign'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        hour: ${{ secrets.HOUR }}
        minute: ${{ secrets.MINUTE }}

    - name: Install dependencies
      run: pip install requests apscheduler

    - name: Run Python script
      run: python test.py --username username --password password --hour hour --minute minute
