name: 'Auto Sign'

on:
  push:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests apscheduler

    - name: Run Python script
      run: python test.py
